# Welcome to Jekyll!
#

# Site settings
title: Specialist Supported Living Limted
description: Delivering creative housing solutions to the supported living sector
owner: Specialist Supported Living Limted
first_published: 2017
email: info@specialistsupportedliving.co.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "specialistsupportedliving.co.uk" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/chris-musson-49a14754
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
